export const Actions = {
    DARK_MODE: 'DARK_MODE',
    SET_USER_INFO: 'SET_USER_INFO',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    IS_ADDED_TO_CART: 'IS_ADDED_TO_CART',
    IS_REMOVED_FROM_CART: 'IS_REMOVED_FROM_CART',
    INTERNET_CONNECTION: 'INTERNET_CONNECTION',
}