import { View, Text, ScrollView, StyleSheet } from 'react-native'
import React from 'react'
import CommonHeader from '../../component/CommonHeader'
import { Colors } from '../../common/Colors';
import { Fonts } from '../../common/Fonts';

const TermsAndConditions = (props: any) => {
    const { navigation } = props;
    return (
        <View className='flex flex-1 bg-whiteColor'>
            <CommonHeader navigation={navigation} title='Terms & Conditions' isCartIcon={false} />
            <ScrollView contentContainerStyle={styles.contentContainer}>
                <Text style={styles.h1}>Clikshop Terms & Condition</Text>
                <Text style={[styles.h2, { marginTop: 20 }]}>Welcome to Clikshop. </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    This document is an electronic record in terms of Information Technology Act,
                    2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.
                    This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules,
                    2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name www.Clikshop.co.in.
                    The Domain Name  www.Clikshop.co.in (the website),
                    including the related mobile application and mobile site (hereinafter referred to as “Platform”, “website”) is owned and operated by clikshop,
                    a company incorporated under the Companies Act, 1956, with its registered office at Shop No - 53, Ward No - 46, Near Gayatri Temple, Shyama Prasad Mukharjee Nagar,
                    Bilaspur 495001 Chhattisgarh India. And Operational Office Near Milestone Apartment  Shop. no.2 Devpuri, Raipur Pin Code: “492001, India.
                    Your use of the Website and its services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Website including the applicable policies which are incorporated herein by way of reference.
                    If You transact on the Website, You shall be subject to the policies that are applicable in the Website for such transactions. By mere use of the Website, You shall be contracting with Clikshop and these terms and conditions including the policies constitute Your binding obligations,
                    with Clikshop. For the purpose of these Terms of Use, wherever the context so requires "You" ,“Your” , “Yourself” ,
                    "User" shall mean any natural or legal person who has agreed to become a buyer or seller on the Website by providing Registration Data while registering on the Website as Registered User
                    using the computer systems. Clikshop allows the User to surf the Website without registering on the Website( whereas for placing an order you need to register yourself) .
                    The term "We", "Us", "Our" shall mean ‘Clikshop’. When You use any of the services provided by Us through the Website, including but not limited to, (e.g. Product Reviews,
                    Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use.
                    We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes.
                    Your continued use of the Website following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, nonexclusive,
                    non transferable, limited privilege to enter and use the Website. ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE,
                    SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Clikshop (including but not limited to Privacy Policy available on privacy policy) as amended  from time to time.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}>Membership Criteria</Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    Transaction on the Platform is available only to persons who can form legally
                    binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within
                    the meaning of the Indian Contract Act, 1872 including minors, undischarged insolvents etc. are not eligible to use
                    the Website. If you are minor i.e. under the age of 18 years, you shall not register as a User of the Clikshop website and
                    shall not transact on or use the website. As a minor if you wish to use or transact on a website,
                    such use or transaction may be made by your legal guardian or parents on the Website.
                    Clikshop reserves the right to terminate your
                    membership and / or refuse to provide you with access to the Website
                    if it is brought to Clikshop's notice or if it is discovered that you are under the age of 18 years
                    and transacting on  the platform.
                </Text>
                <Text style={[styles.h3, { marginTop: 20 }]}> Your Account and Registration Obligations </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    If You use the Website, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Website and refuse to provide You with access to the Website.
                </Text>
                <Text style={[styles.h3, { marginTop: 20 }]}> Platform for Communication  and  Transactions</Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    The Website is a platform that Users utilize to meet and interact with one another for their transactions. Clikshop is not and cannot be a party to or control in any manner any transaction between the Website's Users.
                </Text>
                <Text style={[styles.h3, { marginTop: 20 }]}> Henceforth : </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    1. All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period and mode of delivery, related to products and services. Clikshop does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts are by the Sellers and not by Clikshop.

                    2. At no time shall Clikshop hold any right, title or interest over the products nor shall Clikshop have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Clikshop is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back ordered.

                    3.Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller

                    4. Clikshop does not make any representation or warranty as to the item specifics (such as legal title, creditworthiness, identity, etc) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Website and use Your best judgment on that behalf.

                    5. Clikshop is not responsible for any non performance or breach of any contract entered into between Buyers and Sellers. Clikshop cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Website. Clikshop shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.

                    6.Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in the order by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.

                    7.The Website is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Clikshop is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.

                    8. Clikshop does not make any representation or Warranty as to specifics (such as quality, value, salability, etc) of the products or services proposed to be sold or offered to be sold or purchased on the Website. Clikshop does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Website. Clikshop accepts no liability for any errors or omissions, whether on behalf of itself or third parties.

                    9. Clikshop does not at any point of time during any transaction between Buyer and Seller on the Website come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.

                    10. You shall independently agree upon the manner and terms and conditions of delivery, payment, etc. with the seller(s) that You transact with.

                    11. You release and indemnify Clikshop and/or any of its officers and representatives from any cost, damage, liability or other consequence of any of the actions of the Users of the Website and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Clikshop cannot take responsibility or control the information provided by other Users which is made available on the Website. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Website.

                    Please note that there could be risks in dealing with underage persons or people acting under false pretence.

                    Disclaimer:

                    Pricing on any product(s) as is reflected on the Website may due to some technical issue, typographical error or product information published by the seller may be incorrectly reflected and in such an event the seller may cancel such your order(s).
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Communications </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    When You use the Website or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by other mode of communication, electronic or otherwise.
                </Text>
                <Text style={[styles.h3, { marginTop: 20 }]}> Charges </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    Membership on the Website is free for buyers. Clikshop does not charge any fee for browsing and buying on the Website. Clikshop reserves the right to change its Fee Policy from time to time. In particular, Clikshop may at its sole discretion introduce new services and modify some or all of the existing services offered on the Website. In such an event Clikshop reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Website and such changes shall automatically become effective immediately after they are posted on the Website. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to Clikshop.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Use of the Website </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    You agree, undertake and confirm that Your use of Website shall be strictly governed by the following binding principles:
                    {'\n'}
                    {'\n'}
                    1. You shall not host, display, upload, modify, publish, transmit, update or share any information which:
                    {'\n'}
                    {'\n'}
                    (i) belongs to another person and to which You does not have any right to;
                    {'\n'}
                    {'\n'}
                    (ii)is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;
                    {'\n'}
                    {'\n'}
                    (iii) is misleading in any way;
                    {'\n'}
                    {'\n'}
                    (iv)  is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
                    {'\n'}
                    {'\n'}
                    (v) harasses or advocates harassment of another person;
                    {'\n'}
                    {'\n'}
                    (vi) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";
                    {'\n'}
                    {'\n'}
                    (vii) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or untrue;
                    {'\n'}
                    {'\n'}
                    (viii) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];
                    {'\n'}
                    {'\n'}
                    (ix) promotes an illegal or unauthorized copy of another person's copyrighted work such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
                    {'\n'}
                    (x) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
                    {'\n'}
                    {'\n'}
                    (xi) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
                    {'\n'}
                    {'\n'}
                    (xii)  interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;
                    {'\n'}
                    {'\n'}
                    (xiii) contains video, photographs, or images of another person (with a minor or an adult).
                    {'\n'}
                    {'\n'}
                    (xiv) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
                    {'\n'}
                    {'\n'}
                    (xv) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Clikshop's prior written consent means a communication coming from Clikshop's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;
                    {'\n'}
                    {'\n'}
                    (xvi) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;(xvii)contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
                    {'\n'}
                    {'\n'}
                    (xviii)deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
                    {'\n'}
                    {'\n'}
                    (xix) harm minors in any way;
                    {'\n'}
                    {'\n'}
                    (xx) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;
                    {'\n'}
                    {'\n'}
                    (xxi) violates any law for the time being in force;
                    {'\n'}
                    {'\n'}
                    (xxii) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.
                    {'\n'}
                    {'\n'}
                    (xxiii) impersonate another person;
                    {'\n'}
                    {'\n'}
                    (xxiv) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offense or prevents investigation of any offence or is insulting any other nation.
                    {'\n'}
                    {'\n'}
                    (xxv)contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
                    {'\n'}
                    {'\n'}
                    (xvi) shall not be false, inaccurate or misleading;
                    {'\n'}
                    {'\n'}
                    (xvii). shall not, directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
                    {'\n'}
                    {'\n'}
                    (xvii) shall not create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service provider ("ISPs") or other suppliers;
                    {'\n'}
                    {'\n'}
                    {'\n'}
                    • You shall not use any "deeplink",  "robot", "spider" or other automatic device, program,"page scrape", algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Website. We reserve Our right to bar any such activity.
                    {'\n'}
                    {'\n'}
                    • You shall not probe, scan or test the vulnerability of the Website or any network connected to the Website nor breach the security or authentication measures on the Website or any network connected to the Website. You may not reverse lookup, trace or seek to trace any information on any other User of or visitor to Website, or any other customer, including any account on the Website not owned by You, to its source, or exploit the Website or any service or information made available or offered by or through the Website, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Website.
                    {'\n'}
                    {'\n'}
                    • You shall not attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any server, computer, network, or to any of the services offered on or through the Website, by hacking, password "mining" or any other illegitimate means.
                    {'\n'}
                    {'\n'}
                    • You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the term Clikshop or otherwise engage in any conduct or action that might tarnish the image or reputation, of Clikshop or sellers on platform or otherwise tarnish or dilute any Clikshop's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us.
                    {'\n'}
                    {'\n'}
                    • You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Website or Clikshop's systems or networks, or any systems or networks connected to Clikshop.
                    {'\n'}
                    {'\n'}
                    • You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Website, or with any other person's use of the Website.
                    {'\n'}
                    {'\n'}
                    • You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Website or any service offered on or through the Website. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.
                    {'\n'}
                    {'\n'}
                    • You may not use the Website or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Clikshop and / or others.
                    {'\n'}
                    {'\n'}
                    • You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT) Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services.You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.
                    {'\n'}
                    {'\n'}
                    • Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a nonexclusive, worldwide, perpetual, irrevocable, royalty free, sublicensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Website.
                    {'\n'}
                    {'\n'}
                    • From time to time, You shall be responsible for providing information relating to the products or services proposed to be sold by You. In this connection, You undertake that all such information shall be accurate in all respects. You shall not exaggerate or over emphasize the attributes of such products or services so as to mislead other Users in any manner.
                    {'\n'}
                    {'\n'}
                    • You shall not engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Website or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Website. It shall be a violation of these Terms of Use to use any information obtained from the Website in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to protect Our Users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other Users in any 24-hour period which We deems appropriate in its sole discretion. You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Website) as necessary to satisfy any law, regulation or valid government request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
                    We reserve the right, but has no obligation, to monitor the materials posted on the Website. Clikshop shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spiritor letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect Clikshop views. In no event shall Clikshop assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libellous, tortious, or otherwise unlawful information. It is possible that other users (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Website and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Website, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Website You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Website. Please carefully select the type of information that You publicly disclose or share with others on the Website. Clikshop shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services). Contents Posted on Site All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, "Content"), is a third party user generated content and Clikshop has no control over such third party user generated content as Clikshop is merely an intermediary for the purposes of this Terms of Use. Except as expressly provided in these Terms of Use, no part of the Website and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring") to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without Clikshop's express prior written consent. You may use information on the products and services purposely made available on the Website for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, noncommercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media,(3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents. You shall be responsible for any notes, messages, emails, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Website (collectively, "Content"). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Privacy </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our current Privacy Policy is available at privacy policy. If You object to Your Information being transferred or used in this way please do not use Website. We will share / sell / transfer / license / convey some or all of your personal information with another business entity should we (or our assets) plan to merge with or are acquired by that business entity, or reorganization, amalgamation, restructuring of business or for any other reason whatsoever. Should such a transaction or situation occur, the other business entity or the new combined entity will be required to follow the privacy policy with respect to your personal information. Once you provide your information to us, you provide such information to us and we may use such information to provide you various services with respect to your transaction whether such transactions are conducted on www.Clikshop.co.in or with third party merchant's or third party merchant's website.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}>  Disclaimer of Warranties and Liability </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    All the materials and products (including but not limited to software) and services, included on or otherwise made available to You through Platform are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Clikshop does not warrant that: Platform will be constantly available, or available at all or The information on Platform is complete, true, accurate or non-misleading. All the Products sold on Platform are governed by different state laws and if Seller is unable to deliver such Products due to implications of different state laws, Seller will return or will give credit for the amount (if any) received in advance by Seller from the sale of such Product that could not be delivered to You. You will be required to enter a valid phone number while placing an order on the Platform. By registering Your phone number with us, You consent to be contacted by Us via phone calls and/or SMS notifications, in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Selling on clikshop  </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    As a registered seller, you are allowed to list item(s) for sale on the Website in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Website. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Website. All listed items must be kept in stock for successful fulfillment of sales. The listing description of the item must not be misleading and must describe the actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Website.

                    Clikshop reserves the right to delete such multiple listings of the same product listed by you in various categories.
                </Text>
                <Text style={[styles.h3, { marginTop: 20 }]}>  E-Platform for Communication:  </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    You agree, understand and acknowledge that Clikshop is an online platform that enables you to purchase products listed on the Platform at the price indicated therein at any time. You further agree and acknowledge that Clikshop is only a facilitator and is not and cannot be a party to or control in any manner any transactions on Clikshop.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Payment  </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    While availing any of the payment method/s available on the Website, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:

                    • 1. Lack of authorization for any transaction/s, or
                    {'\n'}
                    {'\n'}
                    • 2. Exceeding the preset limit mutually agreed by You and between "Bank/s", or
                    {'\n'}
                    {'\n'}
                    • 3. Any payment issues arising out of the transaction, or
                    {'\n'}
                    {'\n'}
                    4. Decline of transaction for any other reason/s All payments made against the purchases/services on Website by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Website will not facilitate transactions with respect to any other form of currency with respect to the purchases made on Website.

                    Before shipping / delivering your order to you, Seller may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to Our Users. Further;
                    {'\n'}
                    {'\n'}
                    1. Transactions, Transaction Price and all commercial terms such as Delivery, Dispatch of products and/or services are as per principal to principal bipartite contractual obligations between Buyer and Seller and payment facility is merely used by the Buyer and Seller to facilitate the completion of the Transaction. Use of the payment facility shall not render Clikshop liable or responsible for the non delivery, non receipt, non payment, damage, breach of representations and warranties, non provision of after sales or warranty services or fraud as regards the products and /or services listed on Clikshop's Website.
                    {'\n'}
                    {'\n'}
                    2. You have specifically authorized Clikshop or its service providers to collect, process, facilitate and remit payments and / or the Transaction Price electronically or through Cash on Delivery to and from other Users in respect of transactions through Payment Facility. Your relationship with Clikshop is on a principal to principal basis and by accepting these Terms of Use you agree that Clikshop is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed on Clikshop's Website that are paid for by using the Payment Facility. Clikshop does not guarantee the identity of any User nor does it ensure that a Buyer or a Seller will complete a transaction.
                    {'\n'}
                    {'\n'}
                    3. You understand, accept and agree that the payment facility provided by Clikshop is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment through Cash On Delivery, collection and remittance facility for the Transactions on the Clikshop Website using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility, Clikshop is neither acting as trustees nor acting in a fiduciary capacity with respect to the Transaction or the Transaction Price.

                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Payment Facility for Buyers: </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    • You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Seller to purchase the products and /or services from the Seller using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank to the Seller using Payment Facility.
                    {'\n'}
                    {'\n'}
                    • You, as a Buyer, may agree with the Seller through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent novation / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.
                    {'\n'}
                    {'\n'}
                    • You, as a Buyer, shall electronically notify Payment Facility using the appropriate Clikshop Website features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the receipt of products or services.
                    {'\n'}
                    {'\n'}
                    • You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Website features within the stipulated time than this would make You ineligible for a refund.
                    {'\n'}
                    {'\n'}
                    • You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services
                    {'\n'}
                    {'\n'}
                    • Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received.
                    {'\n'}
                    {'\n'}
                    • For Cash On Delivery transactions, refunds, if any, will be made via demand draft in favour of the Buyer (As per registration details provided by the Buyer)
                    For Pay On delivery transactions, refunds, if any,  shall be made at the same Issuing Bank from where Transaction Price was received.
                    {'\n'}
                    {'\n'}
                    • Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.
                    {'\n'}
                    {'\n'}
                    • For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India (RBI).
                    {'\n'}
                    {'\n'}
                    • Refund shall be conditional and shall be with recourse available to Clikshop in case of any misuse by Buyer. • Refund shall be subject to Buyer complying with Policies.
                    {'\n'}
                    {'\n'}
                    4. Clikshop reserves the right to impose limits on the number of Transactions or Transaction Price which Clikshop may receive from on an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual Buyer during any time period, and reserves the right to refuse to process Transactions exceeding such limit.
                    {'\n'}
                    {'\n'}
                    5. Clikshop reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any agreements by Buyer with Clikshop or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.
                    {'\n'}
                    {'\n'}
                    6. Clikshop may do such checks as it deems fit before approving the receipt of/Buyers commitment to pay (for Cash On Delivery transactions) Transaction Price from the Buyer for security or other reasons at the discretion of Clikshop. As a result ofsuch check if Clikshop is not satisfied with the creditability of the Buyer or genuineness of the Transaction / Transaction Price, it will have the right to reject thereceipt of / Buyers commitment to pay Transaction Price.
                    {'\n'}
                    {'\n'}
                    7. Clikshop may delay notifying the payment confirmation i.e. informing Seller to Dispatch, if Clikshop deems suspicious or for Buyers conducting high transaction volumes to ensure safety of the Transaction and Transaction Price. In addition, Clikshop may hold Transaction Price and Clikshop may not inform Seller to Dispatch or remit Transaction Price to law enforcement officials (instead of refunding thesame to Buyer) at the request of law enforcement officials or in the event the Buyer is engaged in any form of illegal activity. 8. The Buyer and Seller acknowledge that Clikshop will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond control of Clikshop.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Compliance with Laws:</Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    •  Buyer and Seller shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and Clikshop Website. Buyer's arrangement with Issuing Bank:
                    {'\n'}
                    {'\n'}
                    • All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.
                    {'\n'}
                    {'\n'}
                    • All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.

                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Limitation of Liability:</Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    In no event will Clikshop be liable for any indirect, punitive, incidental, special, consequential damages or any other damages resulting from:

                    the use or the inability to use the Services or Products unauthorized access to or alteration of the user's transmissions or data breach of condition, representations or warranties by the manufacturer of the Products any other matter relating to the services including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Platform or Service. Clikshop shall not be held responsible for non-availability of the Clikshop during periodic maintenance operations or any unplanned suspension of access to the Clikshop. The User understands and agrees that any material and/or data downloaded at Clikshop is done entirely at Users own discretion and risk and they will be solely responsible for any damage to their mobile or loss of data that results from the download of such material and/or data. To the maximum extend that is permissible under law, Clikshop’s liability shall be limited to an amount equal to the Products purchased value bought by You. Clikshop shall not be liable for any dispute or disagreement between Users. IN NO EVENT SHALL Clikshop BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}>Indemnity</Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    You shall indemnify and hold harmless Clikshop, its owner, licensee, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorneys' fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Applicable Law </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be exclusively in Bilaspur (C.G.) Jurisdictional Issues/Sale in India Only Unless otherwise specified, the material on the Website is presented solely for the purpose of sale in India. Clikshop makes no representation that materials in the Website are appropriate or available for use in other locations/Countries other than India. Those who choose to access this site from other locations/Countries other than India do so on their own initiative and Clikshop is not responsible for supply of products/refund for the products ordered from other locations/Countries other than India, compliance with local laws, if and to the extent local laws are applicable.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Product Description  </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    Clikshop does not warrant that Product description or other content of this Website is accurate, complete, reliable, current, or error free and assumes no liability in this regard.
                </Text>

                <Text style={[styles.h3, { marginTop: 20 }]}> Contact Us </Text>
                <Text style={[styles.h4, { marginTop: 20 }]}>
                    Please contact us for any questions or comments (including all inquiries) regarding this Website. Grievance officer In accordance with Information Technology Act 2000 and rules made thereunder, the name and contact details of the Grievance Officer are provided below:
                    {'\n'}
                    {'\n'}
                    Mr. Lokesh Kesharwani
                    {'\n'}
                    {'\n'}
                    Senior Managing Partner & CEO
                    {'\n'}
                    {'\n'}
                    Shop No - 53, Ward No - 46, Near Gaytri Temple, Shyama Prasad Mukherjee Nagar,
                    {'\n'}
                    {'\n'}
                    Bilaspur 495001, Chhattisgarh
                    {'\n'}
                    {'\n'}
                    India.
                    {'\n'}
                    {'\n'}
                    Phone No. - 8109658338
                    {'\n'}
                    {'\n'}
                    Whatsapp -  8109658338
                    {'\n'}
                    {'\n'}
                    Email - Info@clikshop.co.in , contact@clikshop.co.in
                    {'\n'}
                    {'\n'}
                    Time:
                    {'\n'}
                    {'\n'}
                    Mon-sat
                    {'\n'}
                    {'\n'}
                    (11:00am - 5:00pm)
                </Text>
            </ScrollView>
        </View>
    )
}

const styles = StyleSheet.create({
    contentContainer: {
        padding: 20
    },
    h1: {
        fontSize: 24,
        color: Colors.newTextColor,
        fontFamily: Fonts.LexendMedium
    },
    h2: {
        fontSize: 20,
        color: Colors.newTextColor,
        fontFamily: Fonts.LexendRegular
    },
    h3: {
        fontSize: 16,
        color: Colors.newTextColor,
        fontFamily: Fonts.LexendRegular
    },
    h4: {
        fontSize: 14,
        color: Colors.newTextColor,
        fontFamily: Fonts.Lexendlight,
        lineHeight: 24
    }
})
export default TermsAndConditions